### ISSUE TITLE
use_legacy_sql is not working when using WITH 

### ISSUE THREAD

**Issue by rontomer** [rstats-db/bigrquery#148]
Hi

Since the last update to use_legacy_sql, I can't run queries when using WITH.
for example 
`query <- "with data as( select 1 as f ) select f from data" 
query_exec(query, project=project$project, use_legacy_sql=F)`

Thanks
Tomer

**Comment by hadley** [comment]
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](https://github.com/jennybc/reprex#what-is-a-reprex)", and follow the advice further down the page.

**Comment by hadley** [comment]
Oh, I just fixed a silly thinko. Should work again now (but in the future a reprex will help me diagnose problems much more quickly)

**Comment by rontomer** [comment]
thanks @hadley 
will do that
