### ISSUE TITLE
Implement BigQuery server authentication (in addition to OAuth)

### ISSUE THREAD

**Issue by mchayat** [rstats-db/bigrquery#22]
For server-side implementations where browser confirmation is not possible, a server side auth can be really handy, as per described below using client ID and a keystore:

https://developers.google.com/bigquery/authorization#service-accounts-server

**Comment by michaelwsherman** [comment]
I had some time to investigate this today, and now I'm up to @Mullefa's `Error: Invalid Credentials`. I used a JSON key about 20 minutes after I generated it. 

The previous problem I was having was related to the JSON key not being RSA.

@craigcitro maybe the reason `PKI` is complaining about `sha256` is because you need to use the latest version on github instead of the CRAN version? That seems to have fixed the same problem for me.

Here's the code that gives the error. It uses the `system` command to delete files named `temp` and `temp2` so make sure you don't have anything important with those names. You'll also need to change the project name in the final line to whatever your project is:
```R
library(devtools)
devtools::install_github("hadley/httr")
devtools::install_github("hadley/bigrquery")
devtools::install_github("s-u/PKI") #for SHA256
library(httr)
library(bigrquery)


endpoint <- oauth_endpoints("google")
secrets <- jsonlite::fromJSON("key.json") #change if necessary
scope <- "https://www.googleapis.com/auth/bigquery"

#Convert secrets$private_key from whatever it comes as from Google to RSA
#openssl must be installed
#I'm sure there is a more elegant way to do this
fileConn<-file("temp")
writeLines(secrets$private_key, fileConn)
close(fileConn)
system("openssl rsa -in temp -out temp2")
secrets$private_key <- scan("temp2",what="character",sep="\n")
system("rm temp")
system("rm temp2")

token <- httr::oauth_service_token(endpoint, secrets, scope)
bigrquery::set_access_cred(token)

sql = "SELECT * FROM [publicdata:samples.wikipedia] LIMIT 10"
query_exec(sql, project=YOUR_PROJECT_NAME) #change to your project
```

The output is:
```
Auto-refreshing stale OAuth token.
Error: Invalid Credentials
```

And setting `sql` to garbage still gives an error (e.g. `sql = "euaoaeuoe"), so the error has nothing to do with the query.

Here's the makeup of my `token`:
```
<Token>
<oauth_endpoint>
 authorize: https://accounts.google.com/o/oauth2/auth
 access:    https://accounts.google.com/o/oauth2/token
 validate:  https://www.googleapis.com/oauth2/v1/tokeninfo
 revoke:    https://accounts.google.com/o/oauth2/revoke
NULL
<credentials> access_token, token_type, expires_in
---
```

I started digging deeper, and can see that sending the `POST` request in `bq_post` returns an error, although perhaps that is obvious. I also see that the token looks very different with normal authorization (*s are a mask for a number):
```
<Token>
<oauth_endpoint>
 authorize: https://accounts.google.com/o/oauth2/auth
 access:    https://accounts.google.com/o/oauth2/token
<oauth_app> google
  key:    4**********7.apps.googleusercontent.com
  secret: <hidden>
<credentials> access_token, token_type, expires_in, refresh_token
```

Any suggestions?

**Comment by brian-bowler** [comment]
@michaelwsherman were you ever able to resolve this? I am running into the same issue.

**Comment by michaelwsherman** [comment]
@brian-bowler I was not. I ended up with a pretty gnarly workaround though. I forked the httr package and essentially removed the interactivity checks. So essentially I have an Oauth session created with a dummy account that will renew when the app tries to do something. The app throws errors when it refreshes the auth, but once the auth is refreshed it works. 

If we ever take the prototype into production I'll try to find the real issue, but for now this workaround is good enough for me. If you find something better please post it here!

So on my shiny server, for the shiny server user in an interactive mode I did a bunch of naughty stuff. This in on a fresh install, from interactive R logged in with the shiny server user. Fresh in the sense I have not installed httr....

#download my wonky httr fork
devtools::install_github("michaelwsherman/httr")

#download bigrquery and whatever else

Then the following commands:
library(bigrquery)
options("httr_oob_default"=TRUE)
query_exec("bigquery command", project="your-project")
You will be asked if you want to use a local file to cache OAuth access. Say "YES"

Then you will get a web site to visit. Whatever credentials you put in here will be tied to your shiny app, so BE CAREFUL.

Now, when your shiny app tries to use bigrquery, it *should* use these credentials you supplied, and my buster httr fork should stop the interactive mode errors.

Let me know if you have followup questions. It's been awhile since I did this but I'll try my best to answer.

**Comment by tnb1234** [comment]
I tried to solve the problem the following way.
I started with the .p12 file, using OpenSSL I converted it to .PEM and then to .RSA file.
Here are the commands: 
pkcs12 -in key.p12 -out key1.pem -nocerts
rsa -in key1.pen -out rsakey.pem

Then I used the content in the rsakey.pem and substituted that for secrets$private_key.

I get a token from google, however when I try to execute the query I receive the error: invalid hash specification.
I suspect that bigrquery::set_access_cred(token) is broken because the token that is otherwise generated I was able to validated through the Google Developers Playground (https://developers.google.com/oauthplayground)

**Comment by divyangashah** [comment]
hi @michaelwsherman bymistake after selecting YES, I have inserted wrong credentials and given Error: Invalid Credentials. how can I solve this. please, help. it gives same error every time.

**Comment by samfield** [comment]
Well back on topic; this will be a poor attempt to recap. 

Should one assume functionality or find functionality in a combination of httr and bigrquery? Is there an verified observation from set_access_cred or should I assume working functionality?

Would I be wrong in recapping:
There have been some valued refactoring even during December '15 for auth.R but my understanding is that the issue still remains open. The current CRAN version reveals set_access_cred function; which assumes you run:

`endpoint_gce <- oauth_endpoints("google")
secrets_gce <- jsonlite::fromJSON("<string_path_to.json>")
scope_gce_bigqr <- c("https://www.googleapis.com/auth/bigquery")

token <- oauth_service_token(
  endpoint = endpoint_gce,
  secrets = secrets_gce,
  scope = scope_gce_bigqr)
`

and the current version available from CRAN states for set_access_cred: 
```
function (value) 
{
  bq_env$access_cred <- value
}

```
for me the resolution of implementing this is:

```
set_access_cred(token)

query_exec(project = projectid, default_dataset = datasetid, query = "SELECT value FROM prices LIMIT 5")

```
and for me this results in 
Error:

If I understand correctly the current dev version in github reveals set_service_token which takes the path of json as input. Does this seem to resolve  the issue?

**Comment by samfield** [comment]
A moment later I extracted my radar from my nether regions and concluded that at least for me; the solution lies in rolling back to httr 1.0.0 as per [issue 86](https://github.com/rstats-db/bigrquery/issues/86). Alternative to use dev version.

**Comment by natekupp** [comment]
Any updates here? Would love to use bigrquery with JSON credentials for a service account.

**Comment by gautiese** [comment]
Guys just uninstall the httpuv package.
After that Rstudio will insist on a command line based authentication.

**Comment by j450h1** [comment]
I believe this is resolved with the function:

set_service_token()

Tested out and works successfully!

**Comment by hadley** [comment]
`set_service_token(path)` is working for me in the bigrquery tests.
