### ISSUE TITLE
UTF-8

### ISSUE THREAD

**Issue by hadley** [rstats-db/bigrquery#45]
Should check that on windows (which doesn't use UTF-8) `standardise_csv()` converts to UTF-8 on write, and maintains UTF-8 encoding status on read

**Comment by krlmlr** [comment]
I guess a more robust approach would be to use JSON for uploading instead of CSV. jsonlite seems to work fine with UTF-8 on Windows (https://github.com/jeroenooms/jsonlite/issues/42). Another advantage: I've run into problems with corner cases such as a one-row one-column data frame with an empty value, this probably won't be an issue when JSON is used.

**Comment by hadley** [comment]
And now worth considering if we should use DML: https://cloud.google.com/bigquery/docs/reference/standard-sql/data-manipulation-language (but probably slower than json)
